use axum::{
    extract::{Path, State},
    http::header,
    response::{IntoResponse, Response},
    routing::get,
    Router,
};
use uuid::Uuid;

use crate::error::AppError;
use crate::middleware::AuthUser;
use crate::models::{RequestStatus, UserRole, VmConfig, VmRequest};
use crate::AppState;

pub fn router() -> Router<AppState> {
    Router::new().route("/:id/terraform", get(generate_terraform))
}

async fn generate_terraform(
    State(state): State<AppState>,
    auth_user: AuthUser,
    Path(id): Path<Uuid>,
) -> Result<Response, AppError> {
    // Fetch the request
    let request = sqlx::query_as::<_, VmRequest>("SELECT * FROM vm_requests WHERE id = $1")
        .bind(id)
        .fetch_optional(&state.db)
        .await?
        .ok_or(AppError::NotFound("VM request not found".to_string()))?;

    // Check access: admins/approvers can generate for any, requesters only their own
    if auth_user.role == UserRole::Requester && request.requester_id != auth_user.id {
        return Err(AppError::Forbidden);
    }

    // Only generate for approved requests
    if request.status != RequestStatus::Approved {
        return Err(AppError::Validation(
            "Terraform can only be generated for approved requests".to_string(),
        ));
    }

    // Fetch VM configs
    let vm_configs = sqlx::query_as::<_, VmConfig>(
        "SELECT * FROM vm_configs WHERE request_id = $1 ORDER BY created_at",
    )
    .bind(id)
    .fetch_all(&state.db)
    .await?;

    // Generate Terraform configuration
    let terraform_config = generate_vsphere_terraform(&request, &vm_configs);

    // Return as downloadable file
    let filename = format!("terraform-{}.tf", request.id);

    Ok((
        [
            (header::CONTENT_TYPE, "text/plain; charset=utf-8"),
            (
                header::CONTENT_DISPOSITION,
                &format!("attachment; filename=\"{}\"", filename),
            ),
        ],
        terraform_config,
    )
        .into_response())
}

fn generate_vsphere_terraform(request: &VmRequest, vms: &[VmConfig]) -> String {
    let mut config = String::new();

    // Header comment
    config.push_str(&format!(
        r#"# Terraform Configuration for VM Request: {}
# Request ID: {}
# Generated by VM Provisioning Portal
#
# IMPORTANT: Update the variables below with your vSphere credentials and infrastructure details

"#,
        request.title, request.id
    ));

    // Terraform and provider configuration
    config.push_str(
        r#"terraform {
  required_version = ">= 1.0.0"
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = ">= 2.0.0"
    }
  }
}

# =============================================================================
# VARIABLES - Update these with your vSphere environment details
# =============================================================================

variable "vsphere_server" {
  description = "vSphere server address"
  type        = string
}

variable "vsphere_user" {
  description = "vSphere username"
  type        = string
}

variable "vsphere_password" {
  description = "vSphere password"
  type        = string
  sensitive   = true
}

variable "datacenter" {
  description = "vSphere datacenter name"
  type        = string
  default     = "Datacenter"
}

variable "cluster" {
  description = "vSphere cluster name"
  type        = string
  default     = "Cluster"
}

variable "datastore" {
  description = "vSphere datastore name"
  type        = string
  default     = "datastore1"
}

variable "network" {
  description = "vSphere network name"
  type        = string
  default     = "VM Network"
}

variable "template_folder" {
  description = "Folder containing VM templates"
  type        = string
  default     = "Templates"
}

# =============================================================================
# PROVIDER CONFIGURATION
# =============================================================================

provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_user
  password             = var.vsphere_password
  allow_unverified_ssl = true
}

# =============================================================================
# DATA SOURCES
# =============================================================================

data "vsphere_datacenter" "dc" {
  name = var.datacenter
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "datastore" {
  name          = var.datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.network
  datacenter_id = data.vsphere_datacenter.dc.id
}

"#,
    );

    // Generate template data sources for each unique OS type
    let mut os_types: Vec<&str> = vms.iter().map(|vm| vm.os_type.as_str()).collect();
    os_types.sort();
    os_types.dedup();

    for os_type in &os_types {
        let template_name = os_to_template_name(os_type);
        let resource_name = os_to_resource_name(os_type);
        config.push_str(&format!(
            r#"data "vsphere_virtual_machine" "template_{}" {{
  name          = "${{var.template_folder}}/{}"
  datacenter_id = data.vsphere_datacenter.dc.id
}}

"#,
            resource_name, template_name
        ));
    }

    // Generate VM resources
    config.push_str(
        r#"# =============================================================================
# VIRTUAL MACHINES
# =============================================================================

"#,
    );

    for vm in vms {
        let resource_name = vm.vm_name.replace('-', "_").replace('.', "_");
        let template_resource = os_to_resource_name(&vm.os_type);

        config.push_str(&format!(
            r#"resource "vsphere_virtual_machine" "{resource_name}" {{
  name             = "{vm_name}"
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = "VMs"

  num_cpus = {cpu_cores}
  memory   = {ram_mb}
  guest_id = data.vsphere_virtual_machine.template_{template_resource}.guest_id

  scsi_type = data.vsphere_virtual_machine.template_{template_resource}.scsi_type

  network_interface {{
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template_{template_resource}.network_interface_types[0]
  }}

  disk {{
    label            = "disk0"
    size             = {storage_gb}
    thin_provisioned = data.vsphere_virtual_machine.template_{template_resource}.disks[0].thin_provisioned
  }}

  clone {{
    template_uuid = data.vsphere_virtual_machine.template_{template_resource}.id

    customize {{
      linux_options {{
        host_name = "{vm_name}"
        domain    = "local"
      }}

      network_interface {{
        ipv4_address = "{ip_address}"
        ipv4_netmask = 24
      }}

      ipv4_gateway    = "{gateway}"
      dns_server_list = ["{dns_primary}", "{dns_secondary}"]
    }}
  }}

  tags = [
    "managed-by:terraform",
    "request-id:{request_id}"
  ]
}}

"#,
            resource_name = resource_name,
            vm_name = vm.vm_name,
            cpu_cores = vm.cpu_cores,
            ram_mb = vm.ram_gb * 1024,
            storage_gb = vm.storage_gb,
            template_resource = template_resource,
            ip_address = vm.ip_address,
            gateway = vm.gateway,
            dns_primary = vm.dns_primary,
            dns_secondary = vm.dns_secondary,
            request_id = vm.request_id,
        ));
    }

    // Outputs
    config.push_str(
        r#"# =============================================================================
# OUTPUTS
# =============================================================================

"#,
    );

    for vm in vms {
        let resource_name = vm.vm_name.replace('-', "_").replace('.', "_");
        config.push_str(&format!(
            r#"output "{resource_name}_ip" {{
  description = "IP address of {vm_name}"
  value       = "{ip_address}"
}}

"#,
            resource_name = resource_name,
            vm_name = vm.vm_name,
            ip_address = vm.ip_address,
        ));
    }

    config
}

fn os_to_template_name(os_type: &str) -> &str {
    match os_type {
        "ubuntu-22.04" => "ubuntu-22.04-template",
        "ubuntu-20.04" => "ubuntu-20.04-template",
        "debian-12" => "debian-12-template",
        "centos-9" => "centos-stream-9-template",
        "rhel-9" => "rhel-9-template",
        "windows-server-2022" => "windows-server-2022-template",
        "windows-server-2019" => "windows-server-2019-template",
        _ => "generic-linux-template",
    }
}

fn os_to_resource_name(os_type: &str) -> String {
    os_type.replace('-', "_").replace('.', "_")
}
